---
- name: INSTALL CLOUD-SQL-PROXY
  get_url:
    url: "{{ cloud_sql_proxy_download_url }}"
    dest: "{{ cloud_sql_proxy_install_path }}"
    mode: 0755

- name: CONFIGURE CLOUD-SQL-PROXY SERVICE
  template:
    src: cloud-sql-proxy.service.j2
    dest: /etc/systemd/system/cloud-sql-proxy.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd configuration
    - restart cloud-sql-proxy

- name: CLOUD-SQL-PROXY STARTED  
  service:
    name: cloud-sql-proxy.service
    state: started
    enabled: true

